package com;

import com.contoller.BookController;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
@ComponentScan("com")
public class ConsoleApp {
    static void main() {
        ApplicationContext appContext = new AnnotationConfigApplicationContext(ConsoleApp.class);
        JdbcTemplate jdbcTemplate = appContext.getBean(JdbcTemplate.class);
        BookController bookController = appContext.getBean(BookController.class);

        String dbSetup = """
                 CREATE TABLE IF NOT EXISTS books (
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 name VARCHAR(255) NOT NULL,
                 added_at TIMESTAMP );\s
               \s""";
        jdbcTemplate.execute(dbSetup);

        bookController.startMainMenu();
    }
}
