plugins {
    id 'java'
}

group = 'com'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework:spring-context:7.0.8")
    implementation("org.springframework:spring-jdbc:7.0.8")
    implementation("org.postgresql:postgresql:42.7.13")

    testImplementation("org.junit.jupiter:junit-jupiter:6.1.2")
    testImplementation("org.mockito:mockito-junit-jupiter:5.23.0")
    testImplementation 'org.testcontainers:testcontainers:2.0.5'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter:2.0.5'
    testImplementation 'org.testcontainers:testcontainers-postgresql:2.0.5'
    testImplementation("org.springframework:spring-test:7.0.8")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    useJUnitPlatform()
}