package com.repository;

import com.entity.Author;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;


@Repository
public class AuthorRepo {

    private final JdbcTemplate jdbcTemplate;

    @Autowired
    public AuthorRepo(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public Author createRecord(Author author) {
        List<Author> authors = jdbcTemplate.query("SELECT * FROM authors WHERE full_name = ?", new BeanPropertyRowMapper<>(Author.class), author.getFullName());
        if (authors.isEmpty()) {
            KeyHolder keyHolder = new GeneratedKeyHolder();
            jdbcTemplate.update(connection -> {
                PreparedStatement ps = connection.prepareStatement(
                        "INSERT INTO authors (last_name, first_name, full_name, added_at) VALUES (?, ?, ?, ?)"
                        , new String[]{"id"});
                ps.setString(1, author.getLastName());
                ps.setString(2, author.getFirstName());
                ps.setString(3, author.getLastName() + " " + author.getFirstName());
                ps.setObject(4, LocalDateTime.now());

                return ps;
            }, keyHolder);
            author.setId(keyHolder.getKey().intValue());
            return author;
        } else throw new IllegalArgumentException(String.format("Author %s already exists. Record id is: %s",
                author.getFullName(), authors.getFirst().getId()));
    }

    public List<Author> getAllRecords() {
        return jdbcTemplate.query("SELECT * FROM authors", new BeanPropertyRowMapper<>(Author.class));
    }

    public Optional<Author> getRecordById(int id) {
        try {
            return Optional.ofNullable(jdbcTemplate.queryForObject(
                    "SELECT * FROM authors WHERE id = ?",
                    new BeanPropertyRowMapper<>(Author.class), id));
        } catch (EmptyResultDataAccessException ex) {
            return Optional.empty();
        }
    }

    public void initiateDatabase() {
        String dbSetup = """
                  CREATE TABLE IF NOT EXISTS authors (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  last_name VARCHAR(255) NOT NULL,
                  first_name VARCHAR(255) NOT NULL,
                  full_name VARCHAR(255) NOT NULL,
                  added_at TIMESTAMP );\s
                \s""";

        jdbcTemplate.execute(dbSetup);
    }

    public void delete(int id) {
        jdbcTemplate.update("DELETE FROM authors WHERE id = ?", id);
    }
}
