package com.repository;

import com.entity.Book;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public class BookRepo {

    private final JdbcTemplate jdbcTemplate;

    @Autowired
    public BookRepo(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void create(Book book) {
        jdbcTemplate.update("INSERT INTO books (name, publish_year, author_id, added_at) VALUES (?, ?, ?, ?)",
                book.getName(), book.getPublishYear(), book.getAuthorId(), LocalDateTime.now());
    }

    public List<Book> getAll() {
        return jdbcTemplate.query("SELECT * FROM books", new BeanPropertyRowMapper<>(Book.class));
    }

    public List<Book> getRecordsByQuery(String query) {
        return jdbcTemplate.query("SELECT * FROM books WHERE name like ?",
                new BeanPropertyRowMapper<>(Book.class), "%" + query + "%");
    }

    public Optional<Book> getRecordById(int id) {
        try {
            return Optional.ofNullable(jdbcTemplate.queryForObject(
                    "SELECT * FROM books WHERE id = ?",
                    new BeanPropertyRowMapper<>(Book.class), id));
        } catch (EmptyResultDataAccessException ex) {
            return Optional.empty();
        }
    }

    public List<Book> getRecordsByAuthorId(int id) {
        return jdbcTemplate.query("SELECT * FROM books WHERE author_id = ?",
                new BeanPropertyRowMapper<>(Book.class), id);
    }

    public void updateBookAuthor(int bookId, int authorId) {
        jdbcTemplate.update("UPDATE books SET author_id = ? WHERE id = ?", authorId, bookId);
    }

    public void deleteRecord(int id) {
        jdbcTemplate.update("DELETE FROM books WHERE id = ?", id);
    }

    public void initiateDatabase() {
        String dbSetup = """
                  CREATE TABLE IF NOT EXISTS books (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR(255) NOT NULL,
                  publish_year INT,
                  author_id INT NOT NULL,
                  added_at TIMESTAMP,
                  CONSTRAINT fk_books_author
                  FOREIGN KEY (author_id)
                  REFERENCES authors(id));\s
                \s""";

        jdbcTemplate.execute(dbSetup);
    }
}
